// File generated by FlutterFire CLI.
// ignore_for_file: type=lint

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }

    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCH7tXZ7UxiPmtSLpzbRiN_2bUZEVoQetg',
    appId: '1:941054054380:web:8e443ebe634b97bdc9bac9',
    messagingSenderId: '941054054380',
    projectId: 'bano-qabil-exam',
    authDomain: 'bano-qabil-exam.firebaseapp.com',
    storageBucket: 'bano-qabil-exam.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyATVmIYvNcuclJ5jiiY7KkSvvan3P0BQ40',
    appId: '1:941054054380:android:abafbafd09e1b3d3c9bac9',
    messagingSenderId: '941054054380',
    projectId: 'bano-qabil-exam',
    storageBucket: 'bano-qabil-exam.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDiPd2zsv4Z7V033Mz4-d6BWhzREFIcZ44',
    appId: '1:941054054380:ios:0411802b4c63882fc9bac9',
    messagingSenderId: '941054054380',
    projectId: 'bano-qabil-exam',
    storageBucket: 'bano-qabil-exam.firebasestorage.app',
    iosBundleId: 'com.example.banoqabiExam',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDiPd2zsv4Z7V033Mz4-d6BWhzREFIcZ44',
    appId: '1:941054054380:ios:0411802b4c63882fc9bac9',
    messagingSenderId: '941054054380',
    projectId: 'bano-qabil-exam',
    storageBucket: 'bano-qabil-exam.firebasestorage.app',
    iosBundleId: 'com.example.banoqabiExam',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCH7tXZ7UxiPmtSLpzbRiN_2bUZEVoQetg',
    appId: '1:941054054380:web:7577df28d4d3228ec9bac9',
    messagingSenderId: '941054054380',
    projectId: 'bano-qabil-exam',
    authDomain: 'bano-qabil-exam.firebaseapp.com',
    storageBucket: 'bano-qabil-exam.firebasestorage.app',
  );
}
