// File generated by FlutterFire CLI.
// ignore_for_file: type=lint

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }

    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'YOUR_EXISTING_WEB_API_KEY',
    appId: '1:941054054380:web:8e443ebe634b97bdc9bac9',
    messagingSenderId: '941054054380',
    projectId: 'bano-qabil-exam',
    authDomain: 'bano-qabil-exam.firebaseapp.com',
    storageBucket: 'bano-qabil-exam.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'YOUR_EXISTING_ANDROID_API_KEY',
    appId: '1:941054054380:android:abafbafd09e1b3d3c9bac9',
    messagingSenderId: '941054054380',
    projectId: 'bano-qabil-exam',
    storageBucket: 'bano-qabil-exam.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'YOUR_EXISTING_IOS_API_KEY',
    appId: '1:941054054380:ios:2cde0d8430b571bbc9bac9',
    messagingSenderId: '941054054380',
    projectId: 'bano-qabil-exam',
    storageBucket: 'bano-qabil-exam.firebasestorage.app',
    iosBundleId: 'com.example.banoQabilExam',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'YOUR_EXISTING_MACOS_API_KEY',
    appId: '1:941054054380:ios:2cde0d8430b571bbc9bac9',
    messagingSenderId: '941054054380',
    projectId: 'bano-qabil-exam',
    storageBucket: 'bano-qabil-exam.firebasestorage.app',
    iosBundleId: 'com.example.banoQabilExam',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'YOUR_EXISTING_WINDOWS_API_KEY',
    appId: '1:941054054380:web:03805dac129761e6c9bac9',
    messagingSenderId: '941054054380',
    projectId: 'bano-qabil-exam',
    authDomain: 'bano-qabil-exam.firebaseapp.com',
    storageBucket: 'bano-qabil-exam.firebasestorage.app',
  );
}